# --------------------------
# Global Project Configuration
# --------------------------

# Market data
tickers:
  - AAPL
  - SPY
  - TSLA

paths:
  test_data: data/processed
  trained_models: models/trained
  reports: reports/plots

start_date: "2018-01-01"
end_date: "2025-12-31"
data_source: "yfinance" # options: yfinance, alpaca, polygon

# Paths
data_dir: "data/processed/"
raw_data_dir: "data/raw/"
cache_dir: "data/cache/"
models_dir: "models/trained/"
logs_dir: "logs/"
reports_dir: "backtester/reports/"

# Model hyperparameters
lstm:
  units: 64
  epochs: 50
  batch_size: 32
xgboost:
  n_estimators: 500
  max_depth: 5
  learning_rate: 0.05

# Backtester
initial_capital: 10000
transaction_cost: 0.001 # 0.1%
slippage: 0.0005
